version: '3.1'
services:
  APSF:
    image: nginx:1.21-alpine
    restart: always
    privileged: true
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./out:/usr/share/nginx/html/